# Generated by Django 2.0.2 on 2018-02-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pings',
            fields=[
                ('pingid', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('mainstream', models.CharField(max_length=255)),
                ('substream', models.CharField(max_length=255)),
                ('playtype', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PingsSongInfo',
            fields=[
                ('pingid', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
            ],
        ),
    ]
