# Generated by Django 2.0.2 on 2018-03-06 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pings',
            fields=[
                ('pingid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('on_deletion', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('pin_type', models.CharField(max_length=255)),
                ('re_pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PingsSongDetail',
            fields=[
                ('pings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ping.Pings')),
                ('song_id', models.UUIDField()),
                ('song_title', models.CharField(max_length=255)),
                ('artist_id', models.UUIDField()),
                ('artist', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('recorded_on', models.CharField(max_length=255)),
                ('favorites', models.IntegerField()),
                ('is_hidden', models.BooleanField()),
            ],
            bases=('ping.pings',),
        ),
        migrations.CreateModel(
            name='CompositionDetail',
            fields=[
                ('pingssongdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ping.PingsSongDetail')),
                ('composer_id', models.UUIDField()),
                ('composer', models.CharField(max_length=255)),
                ('composer_birthday', models.DateField()),
                ('composer_birthplace', models.CharField(max_length=255)),
                ('composer_living_place', models.CharField(max_length=255)),
                ('composed_place', models.CharField(max_length=255)),
                ('composed_when', models.DateTimeField()),
            ],
            bases=('ping.pingssongdetail',),
        ),
    ]
