image: ubuntu:16.04

services:
  - postgres:latest

variables:
  POSTGRES_DB: pinna_gitlab_ci
  POSTGRES_USER: gitlab_ci
  POSTGRES_PASSWORD: "test_passwd_for_ci"

# Build Stages
stages:
  - Test


# Django Build
build:
  stage: Test
  before_script:
    - apt-get update -qq && apt-get install -y -qq python3 python3-pip python3-dev
    - pip3 install -r ./requirements/locked.txt

  script:
    - python --version
    - mg v
    - cd ./PINNA
    - mg db:migrate
    - python3 manage.py test

  tags:
    - django

  except:
    - features/doc
    - features/artworks
    - features/config
    - features/editor_utils
    - features/tools
    - features/gitlab
