# Build Stages
stages:
  - Environment
  - Django
  - Node.js



Installation:
  image: ubuntu:16.04
  stage: Environment

  before_script:
    - apt-get update
    - apt-get install -y build-essential linux-libc-dev bridge-utils git curl ssh unzip golang wget
    - mkdir /opt/bin
    - echo '192.168.137.20 master' >> /etc/hosts
    - echo '192.168.137.21  node1' >> /etc/hosts
    - wget https://github.com/coreos/etcd/releases/download/v3.0.7/etcd-v3.0.7-linux-amd64.tar.gz
    - tar xzvf etcd-v3.0.7-linux-amd64.tar.gz
    - mv etcd-v3.0.7-linux-amd64/etcd /opt/bin/
    - mv etcd-v3.0.7-linux-amd64/etcdctl /opt/bin/
    - ln -s /opt/bin/etcd /usr/local/bin/etcd
    - ln -s /opt/bin/etcdctl /usr/local/bin/etcdctl
    - chmod 755 /opt/bin/etcd
    - chmod 755 /opt/bin/etcdctl

    - wget https://github.com/coreos/flannel/releases/download/v0.6.1/flanneld-amd64
    - mkdir /opt/flanneld
    - mv flanneld-amd64 /opt/bin/flanneld
    - ln -s /opt/bin/flanneld /usr/local/bin/flanneld
    - chmod 755 /opt/bin/flanneld
    
  script:
    - pyenv install --list
  
  tags:
    - common



# Django Test on Python 3.6
python:3.6:
  image: python:3.6.4
  services:
  - name: postgres:latest
    alias: PS_1
  - name: postgres:latest
    alias: PS_2


  variables:
    PS_1_DB: pinna_gitlab_ci
    PS_1_USER: gitlab_ci
    PS_1_PASSWORD: "test_passwd_for_ci"
    PS_1_HOST: "postgres"

    PS_2_DB: pinna_gitlab_ci_testing
    PS_2_USER: gitlab_ci
    PS_2_PASSWORD: "test_passwd_for_ci"
    PS_2_HOST: "postgres"

  stage: Django
  before_script:
    - pip install --upgrade pip
    - pip install -r ./requirements/locked.txt
    - pip install django-mirage

  script:
    - python --version
    - mg v
    - cd ./PINNA
    - cd ./PINNA
    - rm -f test.sqlite3
    - rm -f db.sqlite3
    - cd ..
    # - mg db:migrate
    - python manage.py migrate
    - python manage.py test

  tags:
    - django

  except:
    - features/doc
    - features/artworks
    - features/config
    - features/editor_utils
    - features/tools
    - features/gitlab



# Django Test on Python 3.7
python:3.7:
  image: python:3.7.0b1-stretch
  services:
  - name: postgres:latest
    alias: PS_1
  - name: postgres:latest
    alias: PS_2


  variables:
    PS_1_DB: pinna_gitlab_ci
    PS_1_USER: gitlab_ci
    PS_1_PASSWORD: "test_passwd_for_ci"
    PS_1_HOST: "postgres"

    PS_2_DB: pinna_gitlab_ci_testing
    PS_2_USER: gitlab_ci
    PS_2_PASSWORD: "test_passwd_for_ci"
    PS_2_HOST: "postgres"

  stage: Django
  before_script:
    - pip install --upgrade pip
    - pip install -r ./requirements/locked.txt
    - pip install django-mirage

  script:
    - python --version
    - mg v
    - cd ./PINNA
    - cd ./PINNA
    - rm -f test.sqlite3
    - rm -f db.sqlite3
    - cd ..
    # - mg db:migrate
    - python manage.py migrate
    - python manage.py test

  tags:
    - django

  except:
    - features/doc
    - features/artworks
    - features/config
    - features/editor_utils
    - features/tools
    - features/gitlab

  allow_failure: true


node:9.6.1:
  image: node:9.6.1
  stage: Node.js

  before_script:
    - npm install -g yarn

  script:
    - cd shell
    - yarn install
    - yarn run build
  
  tags:
    - node



node:8.9.4:
  image: node:8.9.4
  stage: Node.js

  before_script:
    - npm install -g yarn

  script:
    - cd shell
    - yarn install
    - yarn run build
  
  tags:
    - node

  allow_failure: true
