image: ubuntu:16.04

services:
  - name: postgres:latest
    alias: ps-1
  - name: postgres:latest
    alias: ps-2

variables:
  PS-1_DB: pinna_gitlab_ci
  PS-1_USER: gitlab_ci
  PS-1_PASSWORD: "test_passwd_for_ci"
  PS-2_DB: pinna_gitlab_ci_testing
  PS-2_USER: gitlab_ci
  PS-2_PASSWORD: "test_passwd_for_ci"

# Build Stages
stages:
  - Test


# Django Build
build:
  stage: Test
  before_script:
    - apt-get update -qq && apt-get install -y -qq python3 python3-pip python3-dev
    - pip3 install --upgrade pip
    - pip3 install -r ./requirements/locked.txt
    - pip3 install django-mirage

  script:
    - python3 --version
    - mg v
    - cd ./PINNA
    # - mg db:migrate
    - python3 manage.py migrate
    - python3 manage.py test

  tags:
    - django

  except:
    - features/doc
    - features/artworks
    - features/config
    - features/editor_utils
    - features/tools
    - features/gitlab
