############################################################
# CI Stages                                                #
############################################################

stages:
  - Code Climate
  - Validation
  - Django
  - Front Test
  - Build
  - Deploy




############################################################
# Code Climate                                             #
############################################################

codeclimate:
  stage: Code Climate
  image: docker:latest
  tags:
    - common
  before_script: []
  services:
    - docker:dind
  variables:
    SETUP_DB: "false"
    DOCKER_DRIVER: overlay2
    CODECLIMATE_FORMAT: json
  cache: {}
  dependencies: []
  script:
    - apk update && apk add jq
    - ./scripts/codequality analyze -f json > raw_codeclimate.json || true
    # The following line keeps only the fields used in the MR widget, reducing the JSON artifact size
    - jq -c 'map({check_name,description,fingerprint,location})' raw_codeclimate.json > codeclimate.json

  artifacts:
    paths: [codeclimate.json]
    expire_in: 1 week




############################################################
# Environmental Validation                                 #
############################################################
ubuntu:python:
  image: ubuntu:16.04
  stage: Validation
  when: manual

  before_script:
    - apt-get update
    - apt-get install -y curl build-essential git gcc make openssl libssl-dev libbz2-dev libreadline-dev libsqlite3-dev
    - apt-get install -y python3-tk tk-dev python-tk libfreetype6-dev 
    - git clone https://github.com/yyuu/pyenv.git ~/.pyenv
    - export PYENV_ROOT=$HOME/.pyenv
    - export PATH=$PYENV_ROOT/bin:$PATH
    - eval "$(pyenv init -)"
    - pyenv --version
    - pyenv install 3.6.4
    - pyenv global 3.6.4
    - pip install pipenv
    
    - sh -c "echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' > /etc/apt/sources.list.d/pgdg.list"
    - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | apt-key add -
    - apt-key list
    - apt-get update
    - apt-get install postgresql -y
    
    
  script:
    - ./ci/scripts/Validation_ubuntu_python_script.sh
  
  tags:
    - common





############################################################
# Django & Backend Test on Python 3.6                      #
############################################################
# Django Test on Python 3.6
python:3.6:
  image: python:3.6.4
  services:
    - name: postgres:latest
      alias: postgre-main
    - name: postgres:latest
      alias: postgre-test
    - name: redis:latest


  variables:
    POSTGRE_MAIN_DB: pinna_gitlab_ci
    POSTGRE_MAIN_USER: gitlab_ci
    POSTGRE_MAIN_PASSWORD: "test_passwd_for_ci"
    POSTGRE_MAIN_HOST: "postgres"

    POSTGRE_TEST_DB: pinna_gitlab_ci_testing
    POSTGRE_TEST_USER: gitlab_ci
    POSTGRE_TEST_PASSWORD: "test_passwd_for_ci"
    POSTGRE_TEST_HOST: "postgres"

  stage: Django
  before_script:
    - ./ci/scripts/Django_python_3.6_before_script.sh

  script:
    - python --version
    - mg v
    - cd ./PINNA/
    - python manage.py migrate
    - python manage.py test

  tags:
    - django

  except:
    - features/doc
    - features/artworks
    - features/config
    - features/editor_utils
    - features/tools
    - features/gitlab




############################################################
# Django & Backend Test on Python 3.7                      #
############################################################
# Django Test on Python 3.7
python:3.7:
  image: python:3.7.0b1-stretch
  when: manual
  services:
    - name: postgres:latest
      alias: postgre-main
    - name: postgres:latest
      alias: postgre-test
    - name: redis:latest


  variables:
    POSTGRE_MAIN_DB: pinna_gitlab_ci
    POSTGRE_MAIN_USER: gitlab_ci
    POSTGRE_MAIN_PASSWORD: "test_passwd_for_ci"
    POSTGRE_MAIN_HOST: "postgres"

    POSTGRE_TEST_DB: pinna_gitlab_ci_testing
    POSTGRE_TEST_USER: gitlab_ci
    POSTGRE_TEST_PASSWORD: "test_passwd_for_ci"
    POSTGRE_TEST_HOST: "postgres"

  stage: Django
  before_script:
    - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
    - pip install --upgrade pip
    - pip install -r ./requirements/locked.txt
    - pip install django-mirage

  script:
    - python --version
    - mg v
    - cd ./PINNA
    - cd ./PINNA
    - rm -f test.sqlite3
    - rm -f db.sqlite3
    - cd ..
    # - mg db:migrate
    - python manage.py migrate
    - python manage.py test

  tags:
    - django

  except:
    - features/doc
    - features/artworks
    - features/config
    - features/editor_utils
    - features/tools
    - features/gitlab

  allow_failure: true





############################################################
# Django & Backend Test on PyPy                            #
############################################################

pypy:latest:
  image: pypy:latest
  when: manual
  services:
    - name: postgres:latest
      alias: postgre-main
    - name: postgres:latest
      alias: postgre-test
    - name: redis:latest


  variables:
    POSTGRE_MAIN_DB: pinna_gitlab_ci
    POSTGRE_MAIN_USER: gitlab_ci
    POSTGRE_MAIN_PASSWORD: "test_passwd_for_ci"
    POSTGRE_MAIN_HOST: "postgres"

    POSTGRE_TEST_DB: pinna_gitlab_ci_testing
    POSTGRE_TEST_USER: gitlab_ci
    POSTGRE_TEST_PASSWORD: "test_passwd_for_ci"
    POSTGRE_TEST_HOST: "postgres"

  stage: Django
  before_script:
    - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
    - pip install --upgrade pip
    - pip install -r ./requirements/locked.txt
    - pip install django-mirage

  script:
    - python --version
    - mg v
    - cd ./PINNA
    - cd ./PINNA
    - rm -f test.sqlite3
    - rm -f db.sqlite3
    - cd ..
    # - mg db:migrate
    - python manage.py migrate
    - python manage.py test

  tags:
    - django

  except:
    - features/doc
    - features/artworks
    - features/config
    - features/editor_utils
    - features/tools
    - features/gitlab

  allow_failure: true


############################################################
# React & front Test by Jest on Node.js 9.7.1              #
############################################################
jest:9.8.0:
  image: node:9.8.0
  stage: Front Test

  before_script:
    - npm install -g yarn

  script:
    - cd shell
    - yarn install
    - yarn run build
  
  tags:
    - node




############################################################
# React & front Test by Jest on Node.js 8.9.4              #
############################################################
jest:8.9.4:
  image: node:8.9.4
  stage: Front Test
  when: manual

  before_script:
    - npm install -g yarn

  script:
    - cd shell
    - yarn install
    - yarn run build
    - yarn run test:sass
    
  
  tags:
    - node

  allow_failure: true



############################################################
# Sass Test                                                #
############################################################

sass:
  image: node:9.7.1
  stage: Front Test

  before_script:
    - npm install -g yarn

  script:
    - cd shell
    - yarn install
    - yarn run test:sass
  
  tags:
    - node



############################################################
# Pug Test                                                #
############################################################

pug:
  image: node:9.7.1
  stage: Front Test

  before_script:
    - npm install -g yarn

  script:
    - cd shell
    - yarn install
    - yarn build:template
    - yarn build:mail
  
  tags:
    - node







############################################################
# Build Debian Package                                     #
############################################################
build:deb:
  image: ubuntu:16.04
  stage: Build

  before_script:
    - echo "Skip"
    
  script:
    - echo "Skip"
  
  tags:
    - common




############################################################
# Build Container                                          #
############################################################
build:container:
  image: ubuntu:16.04
  stage: Build

  before_script:
    - echo "Skip"
    
  script:
    - echo "Skip"
  
  tags:
    - common

  only:
    - master




############################################################
# Deploy                                                   #
############################################################
deploy:kubernetes:
  image: ubuntu:16.04
  stage: Deploy

  before_script:
    - echo "Skip"
    
  script:
    - echo "Skip"
  
  tags:
    - common

  only:
    - master
