language: python

cache: pip

python:
    - "3.6"
    - "3.7"

sudo: false

env:
    - DJANGO=2.0
    - DJANGO=master

matrix:
    fast_finish: true
    include:
      - python: "3.6"
        env: TOXENV="lint"
    exclude:
      - python: "2.7"
        env: DJANGO=2.0
      - python: "2.7"
        env: DJANGO=master
      - python: "3.4"
        env: DJANGO=master
      - python: "3.5"
        env: DJANGO=master
    allow_failures:
      - env: DJANGO=master

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO
