# Generated by Django 2.0.3 on 2018-03-17 16:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_by', models.CharField(max_length=255)),
                ('optimization_id', models.UUIDField(default=uuid.uuid4)),
                ('influencer', models.CharField(max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
