# Generated by Django 2.0.2 on 2018-03-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServingPages',
            fields=[
                ('site_id', models.UUIDField(primary_key=True, serialize=False)),
                ('template_path', models.FileField(upload_to='files')),
                ('domain', models.CharField(default='ServingPage', max_length=255)),
                ('sub_path', models.CharField(max_length=255)),
                ('parent', models.UUIDField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=255)),
                ('publishing_limitation', models.CharField(default='internal', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HelpPages',
            fields=[
                ('servingpages_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.ServingPages')),
                ('version', models.CharField(max_length=255)),
                ('help_indentification', models.CharField(max_length=255)),
                ('usefull', models.IntegerField()),
                ('unusefull', models.IntegerField()),
                ('need_another_help', models.BooleanField()),
            ],
            bases=('pages.servingpages',),
        ),
        migrations.CreateModel(
            name='LicensePage',
            fields=[
                ('servingpages_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.ServingPages')),
                ('is_serving', models.BooleanField()),
            ],
            bases=('pages.servingpages',),
        ),
        migrations.CreateModel(
            name='RichContentsPages',
            fields=[
                ('servingpages_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.ServingPages')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
            ],
            bases=('pages.servingpages',),
        ),
        migrations.CreateModel(
            name='SimpleTextPages',
            fields=[
                ('servingpages_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.ServingPages')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('contents', models.TextField()),
            ],
            bases=('pages.servingpages',),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('richcontentspages_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.RichContentsPages')),
                ('is_landing', models.BooleanField()),
            ],
            bases=('pages.richcontentspages',),
        ),
    ]
