# Generated by Django 2.0.2 on 2018-03-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServingPages',
            fields=[
                ('site_id', models.UUIDField(primary_key=True, serialize=False)),
                ('template_path', models.FilePathField()),
                ('domain', models.CharField(max_length=255)),
                ('sub_path', models.CharField(max_length=255)),
                ('parent', models.UUIDField()),
                ('published', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('servingpages_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.ServingPages')),
                ('version', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=255)),
            ],
            bases=('pages.servingpages',),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('servingpages_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.ServingPages')),
            ],
            bases=('pages.servingpages',),
        ),
    ]
