#!/bin/sh -e
#
# PINNA
# preinst
#
# Created by Shota Shimazu on 2018/03/15
#
# Copyright (c) 2018 Shota Shimazu All Rights Reserved.
#
# This software is released under the terms of restricted, see LICENSE for detail.
# https://hplab.work/pinna-music/pinna-music/blob/master/LICENSE
#

git clone https://$USER_NAME:$PASSWORD@git.hplab.work/pinna-music/pinna-music.git
cd pinna-music
