# Generated by Django 2.0.3 on 2018-03-11 11:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('credential', models.CharField(default='yGRoeSqiLzEb5SrntLuGyvDheIW4IGKj7hO3AF-3NrfepsLAjRRVmA7iOK2YbIpAVx1brxhc6H7wGyhTlZemwg', max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('useragent', models.CharField(max_length=255)),
                ('is_revoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OneTapLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='EelYlFmkRKhzaxZlnhwnuK2iUa3Zl24U_ChDR-hInVl-4mVOhRrBEtf2DaNBcYvl2OzuspWCPnulKQ6VmKPl1A', max_length=255)),
                ('is_tapped', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_code', models.CharField(default='BFEfLnHaQvY4BnuByyCoSbYunXIGorNX-ZMDO_F-q9jcX_rrbjAAufvzl3VDvFwmtHwDJ_HP3XTw95Lhr2A6cA', max_length=255)),
                ('is_revoked', models.BooleanField(default=False)),
            ],
        ),
    ]
