# Generated by Django 2.0.3 on 2018-03-10 08:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('credential', models.CharField(default='b14c68d725e42d00d837a64ffa8dc6f2217b674d9522d767329e6977ab48560c', max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('device_token', models.UUIDField(default=uuid.uuid4)),
                ('useragent', models.CharField(max_length=255)),
                ('is_revoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OneTapLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_token', models.UUIDField(default=uuid.uuid4)),
                ('is_tapped', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid_email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_revoked', models.BooleanField(default=False)),
            ],
        ),
    ]
