# Generated by Django 2.0.2 on 2018-02-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lambda',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('registry_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
