FORMAT: 1A
HOST: https://api.pinna.mu/

# Authentication
Grant authentication api.

# Entry Point [/api/auth/]

# POST jwt/create/
+ Response 200 (application/json)


# GET /message
+ Response 200 (text/plain)

        Hello World!
