# Generated by Django 2.0.3 on 2018-03-13 17:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.UUIDField(default=uuid.uuid4)),
                ('to_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=1000)),
                ('from_user', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_schedule', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.UUIDField(default=uuid.uuid4)),
                ('to_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=1000)),
                ('from_user', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
