# Generated by Django 2.0.3 on 2018-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artillery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='disp_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
