# Generated by Django 2.0.3 on 2018-03-17 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artillery', '0003_auto_20180317_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmail',
            name='bcc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='contents_type',
            field=models.IntegerField(choices=[(0, 'text/plain'), (1, 'text/html')], default=0),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='disp_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='headers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='reply_to',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='result',
            field=models.IntegerField(choices=[(0, 'success'), (1, 'fail')], default=0),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='to',
            field=models.CharField(max_length=1000),
        ),
    ]
